baseURL = "https://docs.sodafoundation.io/"
languageCode = "en-US"
defaultContentLanguage = "en"
googleAnalytics = "UA-138679091-1"

title = "SODA Documentation"
theme = "hugo-theme-learn"
themesdir = "themes/"
metaDataFormat = "yaml"
defaultContentLanguageInSubdir= true

[params]
  editURL = "https://github.com/sodafoundation/documentation/edit/master/content/"
  description = "Documentation for SODA"
  author = "SODA Authors"
  showVisitedLinks = false
  disableBreadcrumb = false
  disableNextPrev = true
   # Change default color scheme with a variant one. Can be "red", "blue", "green".
  themeVariant = "opensds"
  disableLanguageSwitchingButton = false
  # Order sections in menu by "weight" or "title". Default to "weight"
  ordersectionsby = "weight"

[module]
  [[module.imports]]
    disable = false
    ignoreConfig = false
    ignoreImports = false
    path = "github.com/soda-cdm/documentation"
  [[module.imports.mounts]]
    source = "kahu"
    target = "content/soda-cdm/kahu"
  [[module.imports.mounts]]
    source = "kahu/resources"
    target = "content/soda-cdm/kahu/design_spec/resources"
[outputs]
home = [ "HTML", "RSS", "JSON"]

[markup.goldmark.renderer]
  unsafe = true

[Languages]
[Languages.en]
title = "Documentation for SODA Project"
weight = 1
languageName = "English"

[[Languages.en.menu.shortcuts]]
name = "<i class='fab fa-fw fa-github'></i> GitHub repo"
identifier = "ds"
url = "https://github.com/sodafoundation/api"
weight = 10

[[Languages.en.menu.shortcuts]]
name = "<i class='fas fa-fw fa-anchor'></i> SODA Website"
url = "https://sodafoundation.io"
weight = 11

[[Languages.en.menu.shortcuts]]
name = "<i class='fas fa-fw fa-bullhorn'></i> Credits"
url = "https://docs.sodafoundation.io/credits"
weight = 30

gg good job ww
